---

- name: Ensure that Rsyslog is installed on target host(s)
  package:
    name: rsyslog
    state: present

- name: Deploy Json-convertation template on target host(s)
  template:
    src: 50-json.conf.j2
    dest: /etc/rsyslog.d/50-json.conf
  notify:
    - rsyslog reload

- name: Deploy Json-convertation template on target host(s)
  template:
    src: 60-logstash.conf.j2
    dest: /etc/rsyslog.d/60-logstash.conf
  notify:
    - rsyslog reload
